apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vend-pvc-accesscodes
  namespace: {{ .Values.namespace_name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace_name }}
  name: vend-pvc-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi