kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service_name }}
  namespace: {{ .Values.namespace_name }}
  labels:
    app: vend-app
spec:
  selector:
    app: vend-app
  ports:
    - port: 3000
      name: http
  type: NodePort