apiVersion: v1
kind: Secret
metadata:
  name: github.com-thomassuedbroecker-vend-helm
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/thomassuedbroecker/vend-helm
